platform :ios, '9.0'

use_frameworks!

target 'BPFormsExample' do

  pod 'Masonry', '~> 0.6'
  pod 'JVFloatLabeledTextField', '~> 1.1.0'

  target 'BPFormsExampleTests' do
    inherit! :search_paths
  end

end
